sonar.projectKey=toolbox
sonar.projectName=toolbox

sonar.sources=cmd,internal,main.go
sonar.tests=cmd,internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/vendor/**,**/openspec/**,**/internal/build/assets/**,**/testdata/**

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
