// Package sdd is the canonical registry of Spec-Driven-Development skill
// packs that toolbox can bootstrap repo-locally on `toolbox shell`.
//
// Adding a new skill is a three-step contract:
//  1. Append a Skill row below (alphabetical by Key).
//  2. Add a Renovate customManager entry in renovate.json keyed on the
//     same npm package name.
//  3. If the upstream installer writes generated files into the repo, set
//     GitignoreEntries to a small list of glob patterns that cover every
//     install path. cmd/sdd.go `upsertGitignoreFence` writes a fenced
//     block on `toolbox sdd init <name>`. Skills that produce purely
//     user-authored content (e.g. bmad) leave the field nil.
package sdd

import "strings"

// Env keys consumed by internal/build/assets/entrypoint.sh. Centralised
// here so the encode site (sessionplan.sddEnv) and the decode site (bash
// loop in entrypoint.sh) cannot drift independently.
const (
	EnvEnabled       = "TOOLBOX_SDD_ENABLED"
	EnvWorkspaceHash = "TOOLBOX_SDD_WORKSPACE_HASH"
	EnvSkillPrefix   = "TOOLBOX_SDD_"

	EnvFieldPkg     = "_PKG"
	EnvFieldVersion = "_VERSION"
	EnvFieldBin     = "_BIN"
	EnvFieldSteps   = "_STEPS"
	EnvFieldMarker  = "_MARKER"

	StepSeparator = ";"
)

// SkillEnvKey returns the env var name for a given skill field, e.g.
// SkillEnvKey("gsd", EnvFieldPkg) -> "TOOLBOX_SDD_GSD_PKG".
func SkillEnvKey(key, field string) string {
	return EnvSkillPrefix + strings.ToUpper(key) + field
}

// Skill describes one upstream SDD integration the entrypoint can bootstrap.
//
// InstallSteps tokens MUST be whitespace-free: the bash bootstrap splits a
// step on whitespace and the step list on StepSeparator.
//
// RequiresMarker (when non-empty) is a path under /workspace that must
// exist before the bootstrap runs. Used when first-run init is interactive
// or produces scaffolding the user wants to author manually; subsequent
// shells trigger a non-interactive upgrade.
//
// GitignoreEntries is a small list of glob patterns covering every path
// the upstream installer materialises in the repo. The host-side
// `toolbox sdd init` writes a fenced `.gitignore` block from this list.
// Patterns are preferred over enumerated paths because they survive
// version bumps without drift: a new file shipped by a future installer
// version stays covered as long as it lands under one of the documented
// install roots.
type Skill struct {
	Key              string
	NpmPackage       string
	Version          string
	BinName          string
	InstallSteps     [][]string
	GitignoreEntries []string
	RequiresMarker   string
}

var Skills = []Skill{
	{
		// bmad-method first-run is interactive (module/tool prompts):
		// the user runs `npx bmad-method install` manually once and
		// commits _bmad/. With the marker present, `bmad-method install
		// --yes` triggers the non-interactive Quick Update path.
		Key:            "bmad",
		NpmPackage:     "bmad-method",
		Version:        "6.10.0",
		BinName:        "bmad-method",
		InstallSteps:   [][]string{{"install", "--directory", ".", "--yes"}},
		RequiresMarker: "_bmad",
	},
	{
		// gsd ships per-runtime entry points and the USER-GUIDE does not
		// promise stacking runtime flags. Each call writes to a runtime-
		// scoped path (.claude/ vs .codex/), so the two steps never collide.
		//
		// Claude step uses the skill-form layout, kept workspace-local by
		// pointing --config-dir at ./.claude (#317): since opengsd#2808
		// gsd-core only ever emits hyphen-form suggestions (/gsd-<cmd>,
		// bin/lib/runtime-slash.cjs), which Claude Code routes only for
		// skills/gsd-<cmd>/ installs. The previous --claude --local layout
		// (commands/gsd/*.md → colon-routed /gsd:<cmd>) made every gsd
		// "Next Up" suggestion point at a command that doesn't exist.
		// A bare --global would land in ~/.claude instead — shared across
		// every workspace in the container and persisted on the host via
		// the ~/.toolbox/claude mount — so the workspace-local config-dir
		// keeps the per-workspace sentinel semantics intact.
		// Migration note: re-running over a legacy --local layout cleans
		// .claude/commands/gsd/ but leaves the gsd hooks block in
		// .claude/settings.local.json next to the new settings.json copy
		// (double hook execution) — remove it by hand once (upstream gap).
		//
		// Gitignore strategy: glob patterns over the install roots per
		// runtime (agents/, commands/gsd/ (legacy), gsd-core/ and the old
		// get-shit-done/ name, skills/), gsd-*-prefixed state files, plus
		// the non-gsd-prefixed files the claude installer materialises
		// (hooks/lib/, hooks/managed-hooks-registry.cjs, package.json,
		// settings.json) and codex-side runtime artefacts that live
		// outside those roots (agent .toml siblings generated by codex,
		// hooks/gsd-*, top-level codex config/hooks files patched on each
		// install). gsd-core's spec/phase output lives under .planning/,
		// which is user-authored and committed by default (commit_docs),
		// so it is deliberately NOT fenced here.
		Key:        "gsd",
		NpmPackage: "@opengsd/gsd-core",
		Version:    "1.10.0",
		BinName:    "gsd-core",
		InstallSteps: [][]string{
			{"--claude", "--global", "--config-dir", "./.claude"},
			{"--codex", "--local"},
		},
		GitignoreEntries: []string{
			// Claude runtime install roots + gsd-*-prefixed state files
			// at the .claude/ root (gsd-file-manifest.json,
			// gsd-install-state.json, gsd-migration-journal/, …) +
			// gsd-installed hooks under .claude/hooks/.
			".claude/agents/gsd-*",
			".claude/commands/gsd/",
			".claude/get-shit-done/",
			".claude/gsd-*",
			".claude/hooks/gsd-*",
			".claude/skills/gsd-*/",
			// Dot-prefixed profile sibling (not matched by gsd-*).
			".claude/.gsd-profile",
			// Non-gsd-prefixed claude installer artefacts: shared hook
			// helpers, the managed-hooks index, the hooks' package.json,
			// and the settings.json the skill-form install writes its
			// hooks block into. settings.json is fenced because the
			// installer regenerates it on every bootstrap; a repo that
			// commits a hand-written .claude/settings.json keeps it
			// (gitignore never hides tracked files) — drop the line
			// per-repo if you need to start tracking it later.
			".claude/hooks/lib/",
			".claude/hooks/managed-hooks-registry.cjs",
			".claude/package.json",
			".claude/settings.json",
			// Legacy --claude --local layout wrote the hooks block into
			// settings.local.json instead; keep it fenced so migrated
			// workspaces don't surface it as untracked noise.
			".claude/settings.local.json",
			// Codex runtime install roots + gsd-*-prefixed state files
			// at the .codex/ root + gsd-installed hooks under
			// .codex/hooks/.
			".codex/agents/gsd-*",
			".codex/commands/gsd/",
			".codex/get-shit-done/",
			".codex/gsd-*",
			".codex/hooks/gsd-*",
			".codex/skills/gsd-*/",
			// Dot-prefixed profile sibling (not matched by gsd-*).
			".codex/.gsd-profile",
			// Codex top-level config + hooks index patched on every gsd
			// install (codex owns the filenames, but the content is
			// gsd-driven and regenerated on each bootstrap).
			".codex/config.toml",
			".codex/hooks.json",
		},
	},
	{
		// `--force` only auto-cleans legacy adapter files; re-running on a
		// populated workspace preserves openspec/{specs,changes,config.yaml}.
		// `openspec update` always follows so a version bump regenerates
		// the adapter set even when init reports nothing to do.
		//
		// claude + codex are always installed (no per-tool opt-out), so the
		// init command unconditionally enables both adapter sets.
		Key:        "openspec",
		NpmPackage: "@fission-ai/openspec",
		Version:    "1.8.0",
		BinName:    "openspec",
		InstallSteps: [][]string{
			{"init", "--tools=claude,codex", "--force"},
			{"update"},
		},
		GitignoreEntries: []string{
			// Claude adapter files generated by `openspec init` /
			// `openspec update`. Skills live under .claude/skills/
			// openspec-*, slash commands under .claude/commands/opsx/.
			".claude/skills/openspec-*/",
			".claude/commands/opsx/",
			// Codex skills land in-repo. Codex slash-command prompts
			// install into $CODEX_HOME/prompts/ (outside the workspace)
			// so they need no ignore entry here.
			".codex/skills/openspec-*/",
			// Default scaffold regenerated by `init --force` on every
			// fresh workspace. Commit it only when the user customises
			// `context:` or `rules:` (then drop this line per-repo).
			"openspec/config.yaml",
		},
	},
}

func Lookup(key string) (Skill, bool) {
	for _, s := range Skills {
		if s.Key == key {
			return s, true
		}
	}
	return Skill{}, false
}

func Keys() []string {
	out := make([]string, len(Skills))
	for i, s := range Skills {
		out[i] = s.Key
	}
	return out
}
